### ISSUE TITLE
Introduce caching for the Docker build

### ISSUE THREAD

**Issue by giorgiosironi** [hivereview/thehive#23]
To improve Github Actions build time, as most of the layers could be cached (e.g. until `package.json` changes).

Edit: the actual strategy to do this has to be agreed, may be using Github Actions cache for example, or just a `docker pull` from `latest`.

**Comment by giorgiosironi** [comment]
Depends on https://github.com/libero/prc/issues/2

**Comment by giorgiosironi** [comment]
We don't need to improve CI performance at the moment, takes less than 3 minutes to execute.

**Comment by thewilkybarkid** [comment]
Also wonder if it's possible to only run tests etc if the layers have changed?

**Comment by erkannt** [comment]
[Possible solution](https://github.com/whoan/docker-build-with-cache-action) that worked for reviewer-client:

```
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: libero
          password: "${{ secrets.GITHUB_TOKEN }}"
          image_name: libero/reviewer-client/reviewer-client
          image_tag: ${{ github.sha }}
          registry: docker.pkg.github.com
          build_extra_args: "--build-arg=image_tag=${IMAGE_TAG}"
```

This uses the image registry of the github repo that is available by default and pushes each intermediate layer to it.

We wouldn't be able to simple use our `make` targets to build, but could easily construct an equivalent `docker build` command via `build_extra_args`.
